# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2eeefd3559d4f5143f03e9fde1582e6fb08f40ee2825012a5dfeeaa3c937bc7c283931979e295e57eee8a9b6ae9d068eb56cac379e1266ebdc55756487b31a03

test:
  secret_key_base: 23fd3f8552cdf9bf841668bd186af66965e4311827798c56f08e9fb560cad3428e76c4300c97733ef472ceafa49533d46180dbf7cf771bc8ca3ee9f8bebefb7b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
